[build]
  publish = "."
  command = "echo no build"

[[redirects]]
  from = "/"
  to = "/index1.html"
  status = 200

[[headers]]
  for = "/app.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/firebase-config.js"
  [headers.values]
    Cache-Control = "no-cache"
